In [1]:

import requests
from bs4 import BeautifulSoup
import pandas as pd

#get currency 
in_currency = str(input().upper())

#get the amount in Taiwan Dollars
amount = float(input())

tables = pd.read_html('https://rate.bot.com.tw/xrt?Lang=en-US')
table = tables[0]
# Select only the first five columns of the table using the iloc function:
table = table.iloc[:, :5]
#Rename the columns of the table to more descriptive names:
table.columns = ["Currency", "Cash Buying", "Cash Selling", "Spot Buying", "Spot Selling"]
table.set_index('Currency')

# Find the row containing given currency in the "Currency" column
table_row = table[table['Currency'].str.contains(in_currency)]

# Get the "Cash Buying" value
if not table_row.empty:
    ex_rate = table_row.iloc[0]['Cash Buying']
    if ex_rate == "-":
        ex_rate = table_row.iloc[0]['Spot Buying']
    received_cash = round((amount/float(ex_rate)),3)
    print(f"{received_cash} {in_currency}")
else:
    print("Could not find that currency")
table

zar
100
61.958 ZAR

,Currency,Cash Buying,Cash Selling,Spot Buying,Spot Selling
0,American Dollar (USD) American Dollar (USD),29.97,30.64,30.295,30.445
1,Hong Kong Dollar (HKD) Hong Kong Dollar (HKD),3.713,3.917,3.834,3.904
2,British Pound (GBP) British Pound (GBP),36,38.12,36.895,37.525
3,Australian Dollar (AUD) Australian Dollar (AUD),19.77,20.55,19.985,20.33
4,Canadian Dollar (CAD) Canadian Dollar (CAD),21.66,22.57,21.99,22.32
5,Singapore Dollar (SGD) Singapore Dollar (SGD),22.2,23.11,22.67,22.89
6,Swiss Franc (CHF) Swiss Franc (CHF),32.3,33.5,32.91,33.3
7,Japanese Yen (JPY) Japanese Yen (JPY),0.2215,0.2343,0.2283,0.2333
8,South African Rand (ZAR) South African Rand (...,-,-,1.614,1.704
9,Swedish Krona (SEK) Swedish Krona (SEK),2.53,3.05,2.86,2.98
10,New Zealand Dollar (NZD) New Zealand Dollar (...,18.3,19.15,18.63,18.93
11,Thai Baht (THB) Thai Baht (THB),0.7536,0.9436,0.863,0.909
12,Philippine Peso (PHP) Philippine Peso (PHP),0.4946,0.6266,-,-
13,Indonesian Rupiah (IDR) Indonesian Rupiah (IDR),0.00168,0.00238,-,-
14,Euro (EUR) Euro (EUR),31.92,33.26,32.435,33.035
15,Korean Won (KRW) Korean Won (KRW),0.02162,0.02552,-,-
16,Vietnam Dong (VND) Vietnam Dong (VND),0.00105,0.00146,-,-
17,Malaysian Ringgit (MYR) Malaysian Ringgit (MYR),5.829,7.349,-,-
18,China Yen (CNY) China Yen (CNY),4.31,4.472,4.377,4.437